use java6
go
--Thêm bảng brand
insert into brand(is_active, name_brand) values(0,N'Hunter')
insert into brand(is_active, name_brand) values(0,N'Sandal')
insert into brand(is_active, name_brand) values(0,N'Giày thể thao')
insert into brand(is_active, name_brand) values(0,N'Giày chạy bộ')
insert into brand(is_active, name_brand) values(0,N'Giày đá banh')
insert into brand(is_active, name_brand) values(0,N'Giày tây')
--Thêm bảng product
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Biti’s Hunter Street đế #BÀO x MARVEL Spiderman - Hunter-verse 2k23 edition HSM001898',100,1324000,'UNISEX',1,
N'Giày thể thao Biti’s Hunter Street đế #BÀO MARVEL Spiderman, phiên bản Hunter-verse 2k23 HSM001898 dành cho nam hiện tại là phiên bản được mong đợi nhất hiện nay. Không chỉ “ghi điểm” với thiết kế nam tính và mạnh mẽ, sản phẩm còn có rất nhiều ưu điểm ấn tượng về chất lượng. Tìm hiểu chi tiết hơn tại đây nhé!',GETDATE(),1);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Bit is Hunter Street x Vietmax: Faith Edition HSM008100',100,1568000,'FEMALE',1,
N'Giày thể thao Biti’s Hunter Street đế #BÀO MARVEL Spiderman, phiên bản Hunter-verse 2k23 HSM001898 dành cho nam hiện tại là phiên bản được mong đợi nhất hiện nay. Không chỉ “ghi điểm” với thiết kế nam tính và mạnh mẽ, sản phẩm còn có rất nhiều ưu điểm ấn tượng về chất lượng. Tìm hiểu chi tiết hơn tại đây nhé!',GETDATE(),1);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Biti is Hunter Street Go For Love 2K24 - Mule Edition HSM006000',100,731000,'MALE',1,
N'BST Bit is Hunter Street Go For Love 2K24 - đi để đồng điệu. Cùng nhau, ta bước chung trên thanh xuân rực rỡ này với: 
Thiết kế all-white kết hợp cùng mũ quai si nubuck giả canvas - must have item - dễ làm sạch dù có lấm lem size lầm để chiều mọi nét dịu dàng hay nhiệt thành thời niên thiếu 
Lacetag cool ngầu cùng dây tròn & xoắn - trendy - nổi bật cho bạn tự tin bước đi trong những ngày mưa của thanh xuân',GETDATE(),1);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Biti is Hunter Street Go For Love 2K24 HSM006500',100,731000,'MALE',1,
N'BST Biti is Hunter Street Go For Love 2K24 - đi để đồng điệu. Cùng nhau, ta bước chung trên thanh xuân rực rỡ này với: 
Thiết kế all-white kết hợp cùng mũ quai si nubuck giả canvas - must have item - dễ làm sạch dù có lấm lem size lầm để chiều mọi nét dịu dàng hay nhiệt thành thời niên thiếu 
Lacetag cool ngầu cùng dây tròn & xoắn - trendy - nổi bật cho bạn tự tin bước đi trong những ngày mưa của thanh xuân',GETDATE(),1);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Biti’s Hunter X Dune - 4 Nguyên Tố: LỬA HSM004204',100,1268000,'UNISEX',1,
N'Giày thể thao nam Biti’s Hunter X Dune - 4 Nguyên Tố: LỬA HSM004204 đa năng chiếm được nhiều sự yêu thích của các chàng trai. HSM004204 có thiết kế năng động, màu nổi bật là đôi giày vừa giúp bạn có một khởi đầu ngày mới tràn đầy năng lượng, vừa giúp bạn sải bước tự tin trên đường phố.',GETDATE(),1);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày thể thao nam Biti’s Hunter X Dune - 4 Nguyên Tố: LỬA HSM004205 ',100,1568000,'UNISEX',1,
N'Giày thể thao Biti’s Hunter Street đế #BÀO MARVEL Spiderman, phiên bản Hunter-verse 2k23 HSM001898 dành cho nam hiện tại là phiên bản được mong đợi nhất hiện nay. Không chỉ “ghi điểm” với thiết kế nam tính và mạnh mẽ, sản phẩm còn có rất nhiều ưu điểm ấn tượng về chất lượng. Tìm hiểu chi tiết hơn tại đây nhé!',GETDATE(),1);
--
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Sandal Thể Thao Eva Phun Nam Biti is Hunter HEM000700',100,1314000,'MALE',1,
N'Sandal Thể Thao Eva Phun Nam Bit is Hunter HEM000700 là một sản phẩm rất được phái nam ưa chuộng, vậy, sản phẩm có những ưu điểm như thế nào? Hãy cùng tìm hiểu ngay dưới đây nhé!',GETDATE(),2);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Sandal Thể Thao Eva Phun Nam Bit is HEM000500',100,1224000,'FEMALE',1,
N'Nếu bạn đang cảm thấy bí bách khi mang những đôi giày kín trong những ngày hè oi bức như hiện nay, hãy tham khảo những mẫu sandal giản dị nhưng vẫn mang phong cách lịch sự. Để đáp ứng được tiêu chí đó, chúng tôi xin giới thiệu tới các bạn Sandal Thể Thao Eva Phun Nam Biti is HEM000500. Với thiết kế sandal truyền thống nhưng chất liệu hiện đại tạo nên sự thoải mái khi đeo và bền bỉ theo thời gian. Chắc chắn đây sẽ là lựa chọn đáng cân nhắc. Hãy cùng Biti’s tìm hiểu chi tiết về dòng sản phẩm này nhé!!',GETDATE(),2);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Sandal Nam Biti is Hunter Tonic DEMH00400',100,724000,'FEMALE',1,
N'Nếu bạn cần tìm một đôi giày sandal vừa chất lượng, vừa đẹp mắt thì đừng ngần ngại chọn Sandal Nam Biti is Hunter Tonic DEMH00400. Đây là một sản phẩm lý tưởng, phục vụ nhiều mục đích sử dụng khác nhau. Cùng tìm hiểu nhé!!',GETDATE(),2);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Sandal Eva Phun Nam Biti is BEM001500',100,824000,'MALE',1,
N'Sandal nam Biti is BPM001100 với thiết kế trẻ trung là sự lựa chọn hoàn hảo cho những quý ông yêu thích sự thoải mái và phong cách. Với sản phẩm bạn không chỉ trở nên tự tin và nổi bật với chất lượng mà còn trải nghiệm sự êm ái và tiện lợi trong mọi bước chân.',GETDATE(),2);
--
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Thông Dụng Nam Biti is Basic BSM000600',100,424000,'FEMALE',1,
N'Giày thể thao thông dụng nam Biti is Basic BSM000600 được xem là mẫu giày "quốc dân" chưa bao giờ ngừng hot. Mặc dù đã ra mắt từ rất lâu nhưng đây vẫn được xem là sự lựa chọn hàng đầu cho những bạn yêu thích sự đơn giản. Thiết kế giày full đen hoặc trắng sẽ là điểm nhấn làm rung động biết bao nhiêu tín đồ mê phong cách thời trang hiện đại, trẻ trung. Để hiểu hơn về sản phẩm, cùng xem chi tiết ngay sau đây.',GETDATE(),3);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Trung Cấp Biti is DSM074400',100,329000,'FEMALE',1,
N'Sandal nam Biti is BPM001100 với thiết kế trẻ trung là sự lựa chọn hoàn hảo cho những quý ông yêu thích sự thoải mái và phong cách. Với sản phẩm bạn không chỉ trở nên tự tin và nổi bật với chất lượng mà còn trải nghiệm sự êm ái và tiện lợi trong mọi bước chân.',GETDATE(),3);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Thông Dụng Nam Biti is BSM000700',100,376000,'FEMALE',1,
N'Giày thể thao Biti’s nam đã không còn là cái tên xa lạ với người tiêu dùng. Không chỉ là hình ảnh trẻ trung, năng động và gần gũi giới trẻ, giày thể thao Biti’s còn mang lại sự thoải mái và thời trang. Giày Thể Thao Thông Dụng Nam Biti’s BSM000700 được rất nhiều bạn trẻ lựa chọn bởi kiểu dáng đơn giản nhưng không kém phần tinh tế và sang trọng. Để biết thêm chi tiết về sản phẩm, hãy tham khảo bài viết dưới đây',GETDATE(),3);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam DSM076000',100,424000,'MALE',1,
N'Giày thể thao Biti’s nam đã không còn là cái tên xa lạ với người tiêu dùng. Không chỉ là hình ảnh trẻ trung, năng động và gần gũi giới trẻ, giày thể thao Biti’s còn mang lại sự thoải mái và thời trang. Giày Thể Thao Thông Dụng Nam Biti’s BSM000700 được rất nhiều bạn trẻ lựa chọn bởi kiểu dáng đơn giản nhưng không kém phần tinh tế và sang trọng. Để biết thêm chi tiết về sản phẩm, hãy tham khảo bài viết dưới đây',GETDATE(),3);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam Biti is BSM002300',100,524000,'UNISEX',1,
N'Giày thể thao Biti’s nam đã không còn là cái tên xa lạ với người tiêu dùng. Không chỉ là hình ảnh trẻ trung, năng động và gần gũi giới trẻ, giày thể thao Biti’s còn mang lại sự thoải mái và thời trang. Giày Thể Thao Thông Dụng Nam Biti’s BSM000700 được rất nhiều bạn trẻ lựa chọn bởi kiểu dáng đơn giản nhưng không kém phần tinh tế và sang trọng. Để biết thêm chi tiết về sản phẩm, hãy tham khảo bài viết dưới đây',GETDATE(),3);
--
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Chạy Bộ Nam Bitiis Hunter Running DSMH10000',100,924000,'UNISEX',1,
N'Giày Chạy Bộ Nam Bitiis Hunter Running DSMH10000 là mẫu giày chạy với bộ đế thế hệ vượt trội và công nghệ độc quyền từ BITI’S Hunter không những đem đến sự thoải mái khi vận động mà còn mang đến cho người sử dụng phong cách thể thao năng động và sự ấn tượng cho mọi người.',GETDATE(),4);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Chạy Bộ Nam Bitiis Hunter Running HSM003800',100,144000,'UNISEX',1,
N'Giày Chạy Bộ Nam Bitiis Hunter Running DSMH10000 là mẫu giày chạy với bộ đế thế hệ vượt trội và công nghệ độc quyền từ BITI’S Hunter không những đem đến sự thoải mái khi vận động mà còn mang đến cho người sử dụng phong cách thể thao năng động và sự ấn tượng cho mọi người.',GETDATE(),4);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Chạy Bộ Nam Bitiis Hunter Running Tiger DSMH08300',100,124000,'UNISEX',1,
N'Giày Chạy Bộ Nam Bitiis Hunter Running DSMH10000 là mẫu giày chạy với bộ đế thế hệ vượt trội và công nghệ độc quyền từ BITI’S Hunter không những đem đến sự thoải mái khi vận động mà còn mang đến cho người sử dụng phong cách thể thao năng động và sự ấn tượng cho mọi người.',GETDATE(),4);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Thể Thao Nam BITI’S HUNTER JOGGING FESTIVE: PLUTON COLLECTION HSM004900',100,754000,'UNISEX',1,
N'Giày Chạy Bộ Nam Bitiis Hunter Running DSMH10000 là mẫu giày chạy với bộ đế thế hệ vượt trội và công nghệ độc quyền từ BITI’S Hunter không những đem đến sự thoải mái khi vận động mà còn mang đến cho người sử dụng phong cách thể thao năng động và sự ấn tượng cho mọi người.',GETDATE(),4);
--
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Đá Bóng Nam Bitiis Hunter Football HSM003600',100,399000,'UNISEX',1,
N'Giày thể thao là một “người bạn đồng hành” không thể thiếu đối với các cầu thủ sân bóng. Nếu bạn cần tìm một đôi giày thể thao êm chân, chất lượng thì tham khảo ngay Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401 với mẫu mã đa dạng, màu sắc bắt mắt và chất lượng cao cấp từ thương hiệu Biti’s nhé. ',GETDATE(),5);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Bóng Đá Nam Bitiis Hunter Football Futsal DSMH111000',100,398000,'UNISEX',1,
N'Giày thể thao là một “người bạn đồng hành” không thể thiếu đối với các cầu thủ sân bóng. Nếu bạn cần tìm một đôi giày thể thao êm chân, chất lượng thì tham khảo ngay Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401 với mẫu mã đa dạng, màu sắc bắt mắt và chất lượng cao cấp từ thương hiệu Biti’s nhé. ',GETDATE(),5);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401',100,328000,'UNISEX',1,
N'Giày thể thao là một “người bạn đồng hành” không thể thiếu đối với các cầu thủ sân bóng. Nếu bạn cần tìm một đôi giày thể thao êm chân, chất lượng thì tham khảo ngay Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401 với mẫu mã đa dạng, màu sắc bắt mắt và chất lượng cao cấp từ thương hiệu Biti’s nhé. ',GETDATE(),5);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Bóng Đá Nam Bitiis Hunter Football Gen 2K21 Futsal DSMH07300',100,354000,'UNISEX',1,
N'Giày thể thao là một “người bạn đồng hành” không thể thiếu đối với các cầu thủ sân bóng. Nếu bạn cần tìm một đôi giày thể thao êm chân, chất lượng thì tham khảo ngay Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401 với mẫu mã đa dạng, màu sắc bắt mắt và chất lượng cao cấp từ thương hiệu Biti’s nhé. ',GETDATE(),5);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Bóng Đá Nam Bitiis Hunter Football Futsal DSMH09100',100,424000,'UNISEX',1,
N'Giày thể thao là một “người bạn đồng hành” không thể thiếu đối với các cầu thủ sân bóng. Nếu bạn cần tìm một đôi giày thể thao êm chân, chất lượng thì tham khảo ngay Giày Bóng Đá Nam Bitiis Hunter Football DSMH02401 với mẫu mã đa dạng, màu sắc bắt mắt và chất lượng cao cấp từ thương hiệu Biti’s nhé. ',GETDATE(),5);
--
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Da Nam Bitiis X DMM371880',100,624000,'MALE',1,
N'Giày Mocasin Nam Biti’s BMM000677 “chiều lòng” mọi phái mạnh. Bởi, sản phẩm có thiết kế sang trọng mà hiếm có đôi giày nào có được, chất liệu làm đế/quai chỉn chu và kèm nhiều điều nổi bật không thể phủ nhận khác.',GETDATE(),6);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Mocasin Nam Bitiis BMM000477',100,724000,'MALE',1,
N'Giày Mocasin Nam Biti’s BMM000677 “chiều lòng” mọi phái mạnh. Bởi, sản phẩm có thiết kế sang trọng mà hiếm có đôi giày nào có được, chất liệu làm đế/quai chỉn chu và kèm nhiều điều nổi bật không thể phủ nhận khác.',GETDATE(),6);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Mocasin Nam Bitiis BMM000677',100,824000,'MALE',1,
N'Giày Mocasin Nam Biti’s BMM000677 “chiều lòng” mọi phái mạnh. Bởi, sản phẩm có thiết kế sang trọng mà hiếm có đôi giày nào có được, chất liệu làm đế/quai chỉn chu và kèm nhiều điều nổi bật không thể phủ nhận khác.',GETDATE(),6);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Mocasin Nam Biti`s DMM374770*',100,1224000,'MALE',1,
N'Giày Mocasin Nam Biti’s BMM000677 “chiều lòng” mọi phái mạnh. Bởi, sản phẩm có thiết kế sang trọng mà hiếm có đôi giày nào có được, chất liệu làm đế/quai chỉn chu và kèm nhiều điều nổi bật không thể phủ nhận khác.',GETDATE(),6);
insert into product(product_name,quantity_in_stock, price,gender,is_active,description,create_date,brand_id)
values(N'Giày Tây Boot Nam Bitiis BVM001788',100,1324000,'MALE',1,
N'Giày Mocasin Nam Biti’s BMM000677 “chiều lòng” mọi phái mạnh. Bởi, sản phẩm có thiết kế sang trọng mà hiếm có đôi giày nào có được, chất liệu làm đế/quai chỉn chu và kèm nhiều điều nổi bật không thể phủ nhận khác.',GETDATE(),6);
--Thêm bảng màu
insert into color(color_name,create_date,is_active) values(N'Đen',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Trắng',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Vàng',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Xám',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Xanh dương',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Đỏ',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Cam',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Xanh nhớt',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Hồng',GETDATE(),1)
insert into color(color_name,create_date,is_active) values(N'Nâu',GETDATE(),1)
--Thêm bảng màu chi tiết sản phẩm
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,1) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,1)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,2) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,2)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,3) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,3)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,3) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,3)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,4) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,4)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,4) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,5)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,6) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,6)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,7) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,7)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,7) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,8)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,8) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,8)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,8) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,9)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,9) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,9)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,10) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,10)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,11) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,11)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,12) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,13)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,13) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,14)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,15) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,15)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,16) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,16)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,16) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,16)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,17) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,17)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,17) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,18)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,18) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,18)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,19) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,20)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,21) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,21)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,22) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,22)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,22) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,23)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,23) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,23)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,23) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,24)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,24) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,24)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,25) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,25)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,25) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,26)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,27) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,27)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,28) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,28)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),1,29) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),2,29)
insert into details_color(create_date, color_id, product_id) values (GETDATE(),3,29) 
insert into details_color(create_date, color_id, product_id) values (GETDATE(),4,29)
--thêm bảng size
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'37')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'38')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'39')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'40')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'41')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'42')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'43')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'44')
insert into size(create_date, is_active, size_name) values (GETDATE(),1,N'45')
-- thêm dữ liệu bảng size product
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,1)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,2)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,3)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,4)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,5)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,6)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,7)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,8)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,9)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,10)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,11)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,12)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,13)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,14)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,15)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,16)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,17)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,18)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,19)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,20)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,21)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,22)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,23)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,24)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,25)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,26)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,27)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,28)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 1,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 2,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 3,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 4,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 5,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 6,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 7,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 8,29)
insert into details_size(create_date, size_id,product_id) values (GETDATE(), 9,29)
--thêm bảng giảm giá
insert into discount(discounted_price,status, product_id) values (822000,0,1);
insert into discount(discounted_price,status, product_id) values (322000,0,2);
insert into discount(discounted_price,status, product_id) values (322000,0,3);
insert into discount(discounted_price,status, product_id) values (222000,0,4);
insert into discount(discounted_price,status, product_id) values (222000,0,5);
insert into discount(discounted_price,status, product_id) values (122000,0,6);
insert into discount(discounted_price,status, product_id) values (222000,0,7);
insert into discount(discounted_price,status, product_id) values (322000,0,8);
-- thêm bảng hình ảnh product
insert into product_image(image_name, product_id) values (N'08b_774a037f29d040d3bd57509f7ecd7e47_1024x1024.webp',1)
insert into product_image(image_name, product_id) values (N'dai_dien_rong_6bc6b18f9a5c4056987a02b9d2d9164d_1024x1024.webp',2)
insert into product_image(image_name, product_id) values (N'2_85659db6c4c84ed089be493ad2910459_large.webp',3)
insert into product_image(image_name, product_id) values (N'5_645d1b50df4c4bb387146668ec4c44b6_large.webp',3)
insert into product_image(image_name, product_id) values (N'hsm004400kem1_c93e10abe0f44e409d819a050be47171_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem4_21de11f1790744928f59e4b11bcf998c_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem5_b1b7532ead8c4a94b85e3097efb695e5_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem6_1bb7eb6a19c046cea6c4c6871a146140_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem7_f9acbe6e57604bdea262e2a628a18e5d_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem8_8cfac94e963d4e658786d2e4b9388f47_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004400kem9_21ff9af137fb4fa3a23c0d3f9d34234e_large.webp',4)
insert into product_image(image_name, product_id) values (N'hsm004401den1_58f0020cd4314e309c76dcdd2621ee82_large.webp',5)
insert into product_image(image_name, product_id) values (N'hsm004401den2_2a8d04b8d71f40e09016783233b37e44_large.webp',5)
insert into product_image(image_name, product_id) values (N'hsm004401den3_f796b31f825e46ffa40bb3cb4b914b6b_large.webp',5)
insert into product_image(image_name, product_id) values (N'hhsm004401den3_f796b31f825e46ffa40bb3cb4b914b6b_large.webp',5)
insert into product_image(image_name, product_id) values (N'hsm004401den3_f796b31f825e46ffa40bb3cb4b914b6b_large.webp',6)
insert into product_image(image_name, product_id) values (N'hsm004401den7_876339712bd340d2830cf70d1a40bdec_large.webp',6)
insert into product_image(image_name, product_id) values (N'hsm004401den8_096bd3e2ce2e4dc785018207a3b40f69_large.webp',6)
insert into product_image(image_name, product_id) values (N'hsm004900den2_accdf8f324684748984064eb480bd0ba_large.webp',6)
insert into product_image(image_name, product_id) values (N'hsm004900den3_430d592a33a14489add58555a6245e73_large.webp',6)
insert into product_image(image_name, product_id) values (N'hsm004900den4_92f637fb0fb74276ba74c7865c893183_large.webp',7)
insert into product_image(image_name, product_id) values (N'hsm004900den4_92f637fb0fb74276ba74c7865c893183_large.webp',7)
insert into product_image(image_name, product_id) values (N'bem001500den4_fe1030e4721642b5a17163b743ad2dfd_large.webp',7)
insert into product_image(image_name, product_id) values (N'bem001500den2_dba2cbc0e387424598e8d1ae772630c6_large.webp',8)
insert into product_image(image_name, product_id) values (N'bem001500den6_d341f55277194dd0a6354f24e28a4f95_large.webp',8)
insert into product_image(image_name, product_id) values (N'bem001500den7_cad1376ce74244c796b8eba62f067576_large.webp',8)
insert into product_image(image_name, product_id) values (N'bem001500den8_3e63f44018a1405eb2aec67bb2b45df9_large.webp',9)
insert into product_image(image_name, product_id) values (N'bem001500den6_d341f55277194dd0a6354f24e28a4f95_large.webp',9)
insert into product_image(image_name, product_id) values (N'bem001500den9_6b633b05396c4b6bb65e9b4ab4f2049a_large.webp',9)
insert into product_image(image_name, product_id) values (N'hem000500kem__8__1410dff619d64393ab83040cb2a1219f_large.webp',10)
insert into product_image(image_name, product_id) values (N'hem000500kem__10__3956f6f620de4400a03ca899fa3cb0de_large.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem2_3c0fabb9b99e47cb848d5f9348dd7068_large.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem3_bd0789e6fd9141b69b624875a07897a4_large.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem4_5033cb4f6d37420da5f6055599c57330_largee.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem6_856b03b7dc2440a29a67faac664be7a2_largee.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem7_5cfe22ff21b840d8bd62df524d482d6e_large.webp',10)
insert into product_image(image_name, product_id) values (N'hem000700kem9_637fa5a3ffb440cbb2061a56a3031ac7_large.webp',10)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-sinez-color-den_4259ed81bdea47e5b647137b5ba47228_large.webp',11)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-pdsiy-color-den_b2fa0ba65b824d268638749ec19aa503.webp',11)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-mqo8t-color-den_2065ee169a6446e283af17c4f1f4b8db_large.webp',11)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-mqo8t-color-den_2065ee169a6446e283af17c4f1f4b8db_large (1).webp',11)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-j0k9h-color-den_095d4812f04648b18550fd4ecc78dd91_large.webp',11)
insert into product_image(image_name, product_id) values (N'o-cap-nam-biti-s-hunter-layered-upper-dsmh02800den-den-z5ipu-color-den_87d4aacde3ab449180947890d1b9a83f_large.webp',11)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__10__4455a5e9fa1e44d99aa952a7383ae4db_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__3__fce7a829fcd141afbd47e43cf7411577_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__4__08436427489d4a228707f3617e9796d5_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__5__be206d2ba3884bd392970711275fe6e3_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__6__37482f4cc0e74d5bb9f49801482da39b_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__7__875df280a0a24fb592d6ee161a9b030d_large.webp',12)
insert into product_image(image_name, product_id) values (N'hsm003800xdg__9__e9362bdd96c547c785d65150d4ed90ec_large.webp',12)
insert into product_image(image_name, product_id) values (N'tion-hsm001400xam-xam-kizv5-color-xam_0d142a547ed4448bb86428668620378b_57a805f52f9a4108aeeecad0ec2d555a_large.webp',13)
insert into product_image(image_name, product_id) values (N'hay-bo-nam-biti-s-hunter-running-gray-dsmh10000xam-xam-6q57j-color-xam_a8463c6a86a44bc59c1e908c9a2050ee_large.webp',13)
insert into product_image(image_name, product_id) values (N'tion-hsm001400xam-xam-hhdrg-color-xam_9fe978863fda4eb7ad956a1e391c3711_1bdfe3a2447f49f98eeac8bef18158a4_large.webp',13)
insert into product_image(image_name, product_id) values (N'tion-hsm001400xam-xam-547xe-color-xam_35053e31e9d0434d85cd413d3bc88883_56f1361aefbd42c2a2f57f266d13da75_large.webp',13)
insert into product_image(image_name, product_id) values (N'tion-hsm001400xam-xam-5eg7a-color-xam_d51b700c14a444bfac98b98d7158ee6f_997bdab4488f46528ee94c0e5218fb3b_large.webp',13)
insert into product_image(image_name, product_id) values (N'h08300cam__2__4fbdf6a42c304e00a40b6dd14b9e9bb7_large.webp',14)
insert into product_image(image_name, product_id) values (N'h08300cam__4__8979498e72f24d51b32da75d8cb54a03_large.webp',14)
insert into product_image(image_name, product_id) values (N'h08300cam__5__82dfff6227f94fd48780041d3ecaad6e_large.webp',14)
insert into product_image(image_name, product_id) values (N'h08300cam__6__b8196662746e404ea824287f0498283e_large.webp',14)
insert into product_image(image_name, product_id) values (N'h08300cam__7__ba360eac0541427cb14ce821f40ea6c1_large.webp',14)
insert into product_image(image_name, product_id) values (N'-da-nam-biti-s-hunter-football-futsal-dsmh09100den-den-gop9m-color-den_4242bd6f50a84c44b01995c4377532d9_large.webp',15)
insert into product_image(image_name, product_id) values (N'-da-nam-biti-s-hunter-football-futsal-dsmh09100den-den-t4dta-color-den_768fe58f5a9b4c298fbdeb261f5a9d00_large.webp',15)
insert into product_image(image_name, product_id) values (N'-da-nam-biti-s-hunter-football-futsal-dsmh09100den-den-vz1n3-color-den_8b47660af56b4bb18a83af7e8a4dae66_large.webp',15)
insert into product_image(image_name, product_id) values (N'-da-nam-biti-s-hunter-football-futsal-dsmh09100den-den-xgstj-color-den_a91d1003605343a495511fbd4a36e94b_large.webp',15)
insert into product_image(image_name, product_id) values (N'dsm074400den__1__ebba07f1471643e99690e5e88fa6db80_large.webp',16)
insert into product_image(image_name, product_id) values (N'dsm074400den__3__e759fcde518242c0ab1768f20eadd478_large.webp',16)
insert into product_image(image_name, product_id) values (N'dsm074400den__4__b330ab7411c145f9b0c4d3fe59d3125f_large.webp',16)
insert into product_image(image_name, product_id) values (N'dsm074400den__5__620130938b7d4f79a12176ed12b551c9_large.webp',16)
insert into product_image(image_name, product_id) values (N'dsm074400den__6__88349112e0124c73ae5f313d5ceab2eb_large.webp',16)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-hunter-x-2k22-jet-dsmh02202-i2zmo-color-den_0f907b411b2b497d9c066636d6f13e59_large.webp',17)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-hunter-x-2k22-jet-dsmh02202-luacw-color-den_aa78bf9ad04645369f6bbdb9427a1b33_1024x1024.webp',17)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-hunter-x-2k22-jet-dsmh02202-p8bqd-color-den_cfbe4667ddd440338a3bbf54fc456c87_large.webp',17)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-hunter-x-2k22-jet-dsmh02202-pyl6c-color-den_b946d37c89dd427f9eb8d3a78af234d8_large.webp',17)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-hunter-x-2k22-jet-dsmh02202-z8gx2-color-den_64f6cbbfaefe4e1ca9822d28383b1273_large.webp',17)
insert into product_image(image_name, product_id) values (N'dsm074400den__4__b330ab7411c145f9b0c4d3fe59d3125f_large.webp',18)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-dsm076000den-den-bshso-color-den_965caf96c6484c94851a46553b9a5d5d_large.webp',18)
insert into product_image(image_name, product_id) values (N'hay-bo-nam-biti-s-hunter-running-gray-dsmh10000xam-xam-0mhwh-color-xam_19903831807a42ac974e1fb3be33a70a_large.webp',19)
insert into product_image(image_name, product_id) values (N'hay-bo-nam-biti-s-hunter-running-gray-dsmh10000xam-xam-bbkmo-color-xam_889d079814b7447bb5d4b92b8f068d64_large.webp',19)
insert into product_image(image_name, product_id) values (N'hay-bo-nam-biti-s-hunter-running-gray-dsmh10000xam-xam-6q57j-color-xam_a8463c6a86a44bc59c1e908c9a2050ee_large.webp',19)
insert into product_image(image_name, product_id) values (N'thethao1.webp',20)
insert into product_image(image_name, product_id) values (N'thethao2.webp',20)
insert into product_image(image_name, product_id) values (N'thethao3.webp',20)
insert into product_image(image_name, product_id) values (N'thethao4.webp',20)
insert into product_image(image_name, product_id) values (N'thethao5.webp',20)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-dsm074500den-den-drrjc-color-den_2edf9b98391b41959398ecf3c102bb89_large.webp',21)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-dsm074500den-den-jlkbn-color-den_4af343e192e3417cb45712239ef1d179_large.webp',21)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-dsm074500den-den-punj6-color-den_2bb1db53698349efa51cab1461f08f68_large.webp',21)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-dsm074500den-den-y63v2-color-den_9d4110d772514185802a272ca6495bf5_large.webp',21)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-biti-s-dsm074500den-den-zmsuu-color-den_694111a2ab1f4ff28bdddac6c4ea44e5_large.webp',21)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-dsm076000den-den-08fwt-color-den_0166a244524749ab9f913de63149791a_large.webp',22)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-dsm076000den-den-xg0a2-color-den_4b2ce258749d43b7bb2646793e7dc0ef_large.webp',22)
insert into product_image(image_name, product_id) values (N'giay-the-thao-nam-dsm076000den-den-7zvk9-color-den_9ca0df7ffa8b47e7b69419c73bcd9a48_large.webp',22)
insert into product_image(image_name, product_id) values (N'hsm003600cam__3__d95af1eec7474e41b10c8e723f829750_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__4__c8f18003aac449bb8b85e9d8dde75608_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__5__656911ee3f8b40bdac0ed41a762fd5ee_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__6__53d01a00db48476c9367ec8c85b2fde2_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__7__16c9cb8719ff432e991c305289ac8d19_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__8__f955eb9710ce40df9a72ea85abef0a00_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__9__d2fa5336ea0140a7a65e367d43faa4a5_large.webp',23)
insert into product_image(image_name, product_id) values (N'hsm003600cam__10__37b06c4f3fa54ef8a3999b76afdef645_large.webp',23)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-0fy9d-color-do_c8e502d59d6e4b9eb5c08a5f15f3fd7f_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-4max6-color-do_674871fb05bf4542b60b2cf17b26081a_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-39y5g-color-do_fddb462d66c744829d8d1a7780196e4b_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-jnh1z-color-do_c5d29f523f2544a483c3cf67da6d3459_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-m1ti6-color-do_9fdee24a5e93468489675f73e2e3a255_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-su3sg-color-do_6bdbc2fce4d84cf48fff1ff203c3ad82_large.webp',24)
insert into product_image(image_name, product_id) values (N'giay-bong-da-nam-hunter-football-futsal-dsmh11100doo-do-yrg7z-color-do_3bad260d59894d069a0a288f8c8f73ee_large.webp',24)
insert into product_image(image_name, product_id) values (N'bmm000477nad4_72c9bd75670c44bb984b45ce76aa0062_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000477nad5_0b080650cc2746eeb72545d2602e73a4_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000477nad7_f8489604d15c4260b974206055a73e00_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000477nad8_7435fa11a2c442098c6d5e9e0cd39c7f_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000477nad9_98f482e17f7b485fabd3b15a7b12daf3_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000477nad10_7b66194e5b1843598398f1b70679fa4a_large.webp',25)
insert into product_image(image_name, product_id) values (N'bmm000677den3_6a2c6b2852c948d89d0302432ccd8caf_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den4_02b2ee3f019f479abef3ce3c7c8a018d_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den5_861ee083bf01496d8750a744d948e788_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den6_c68148558c1c4a8ca366a3b665e6e007_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den7_4c81dfe5e31a4e92aaea83d75ae472b7_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den8_1a05cbf1026c4990a5de4e7a995944a5_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den9_15ccdb7d5d2a4dd796a398f52c80aaa9_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677den10_c50791eef2e94462937cc79783f63e9d_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bmm000677nad6_44d8b30c5b80456d9434d896d6bc6217_medium.webp',26)
insert into product_image(image_name, product_id) values (N'bvm001788den3_f26738334bad4b3598275f49b74b2a16_large.webp',27)
insert into product_image(image_name, product_id) values (N'bvm001788den4_0786a2d5a0584f11808b0b98a5d5ce97_large.webp',27)
insert into product_image(image_name, product_id) values (N'bvm001788den5_0f5cd16a01c7494ca47bab0e9eb59719_large.webp',27)
insert into product_image(image_name, product_id) values (N'bvm001788den6_d182239afed041f9ac07a1793d4762af_large.webp',27)
insert into product_image(image_name, product_id) values (N'bvm001788den9_60be194e4a174ca782b90b8168ae305e_large.webp',27)
insert into product_image(image_name, product_id) values (N'bvm001788den10_0ca02458ec2446d8924c871d1476dcdc_large.webp',27)
insert into product_image(image_name, product_id) values (N'ttn_6772_52413b87f7a245768a4c9d70fdf883ec_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6773_e6e04cad48fd4941be3f45ad440bdbc3_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6774_1af2026e193e418589a38ac8cbdfd87e_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6775_0467e986ac6a4e068aa65f68def3022b_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6776_94831e1104f84ad7b903aa065c76ad77_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6777_e528896e4d08408298882a5e83885894_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6778_1b2ac80e7e0f48d6abbac628994a6ae5_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_6779_b7067af4c1da4827ad4b464e1c337d48_large.webp',28)
insert into product_image(image_name, product_id) values (N'ttn_2975_7afa92e928e74778977f5532dee6a2d8_large.webp',29)
insert into product_image(image_name, product_id) values (N'ttn_2980_5c4faf7a87b24b5bb692c31fb6706fd3_large.webp',29)
insert into product_image(image_name, product_id) values (N'ttn_2972_512b42eb729d43b4b044721c740cea1f_large.webp',29)
--Thêm dữ liệu bảng người dùng
insert into _user(birth_day, email, firstname,gender, lastname, password,role) values ('2000/01/01','tuandhpc05076@fpt.edu.vn',N'Đặng','MALE',N'Hoàng Tuấn','sdfsdfsfdfgdflijertihedfgdfg','ADMIN');
insert into _user(birth_day, email, firstname,gender, lastname, password,role) values ('2000/01/01','tuandhpc05077@fpt.edu.vn',N'Đặng','MALE',N'Hoàng Tuấn','sdfsdfsfdfgdflijertihedfgdfg','USER');
insert into _user(birth_day, email, firstname,gender, lastname, password,role) values ('2000/01/01','tuandhpc05078@fpt.edu.vn',N'Đặng','MALE',N'Hoàng Tuấn','sdfsdfsfdfgdflijertihedfgdfg','USER');
--Thêm dữ liệu vào bảng liên hệ
insert into contact(address_name, is_active, is_message, number_phone,user_id) values (N'ấp khánh hội, thị trấn ngã sáu, huyện châu thành, tỉnh hậu giang',0, 0, '0383658814',1)
insert into contact(address_name, is_active, is_message, number_phone,user_id) values (N'ấp khánh hội, thị trấn ngã sáu, huyện châu thành, tỉnh hậu giang',0, 0, '0383658812',2)
insert into contact(address_name, is_active, is_message, number_phone,user_id) values (N'ấp khánh hội, thị trấn ngã sáu, huyện châu thành, tỉnh hậu giang',0, 0, '0383658816',3)
-- Thêm dữ liệu bảng giỏ hàng
insert into cart(cart_id,check_pay, quantity,product_id,id) values ('1dsfsd',0,2,1,1)
insert into cart(cart_id,check_pay, quantity,product_id,id) values ('1dsfsdfsdf',0,2,1,2)

-- thêm dữ liệu vào bảng order
insert into _order(order_id,note,status,total_amount,cart_id,user_id) values ('dfyrhewdferrte',N'Đơn hàng đang chờ giao',N'Đặt hàng',123600,'1dsfsd',1)
insert into _order(order_id,note,status,total_amount,cart_id,user_id) values ('dfyrhewdferrteq',N'Đơn hàng đang chờ giao',N'Đặt hàng',123600,'1dsfsdfsdf',1)
--Thêm dữ liệu bảng thanh toán
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrte',1)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrte',1)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrte',2)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrte',3)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrteq',1)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrteq',1)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrteq',2)
insert into payment(create_at, price, quantity,order_id,product_id) values (GETDATE(), 100000,2,'dfyrhewdferrteq',3)
--Thêm dữ liệu bảng yêu thích
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,1,1);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,2,1);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,3,1);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,4,1);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,5,1);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,6,2);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,7,2);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,8,2);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,9,2);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,10,2);
insert into favorites(create_at,is_delete, product_id,user_id) values (GETDATE(),1,11,2);
--Thêm dữ liệu bảng voucher

